{
  "hash": "2ea7330246e00ae39b1912c2c746f217",
  "result": {
    "engine": "knitr",
    "markdown": "# Ethics Beyond Compliance {#sec-ethics}\n\n::: {.bookepigraph}\n\n\n\n\n\n```{=latex}\n\\begin{flushright}\\small\n```\n\n\n\n\n\n*The first principle is that you must not fool yourself, and\nyou are the easiest person to fool.*\n\n[Richard P. Feynman]{.smallcaps}, *Cargo Cult Science* (1974)\n\n\n\n\n\n```{=latex}\n\\end{flushright}\n```\n\n\n\n\n\n:::\n\n::: {.callout-note}\n## Why this chapter exists\n\nThe book's treatment of ethics has so far been entirely\nregulatory. @sec-federal covers what the funders require,\n@sec-deident covers what the HIPAA Privacy Rule requires, and\n@sec-cdisc covers what the FDA requires. All three are\nnecessary and none is sufficient, because an analysis can\nsatisfy every one of them and still mislead every reader it\nreaches. This chapter is about the failures that compliance\ndoes not prevent, and about which the statistician, not the\ninstitutional review board, is the last line of defense.\n:::\n\n## Prerequisites\n\nAnswer the following questions to see if you can bypass this\nchapter. You can find the answers at the end of the chapter in\n@sec-quiz-answers-02c.\n\n1. A dataset is assembled entirely from information that\n   individuals published about themselves in public. Explain how\n   releasing it can nonetheless harm them.\n2. Two group means have 95% confidence intervals that overlap.\n   May you conclude that the groups do not differ significantly?\n3. Name three ways a figure can mislead a reader without\n   containing a single false number.\n\n## Learning objectives\n\nBy the end of this chapter you should be able to:\n\n- Distinguish the harm of disclosure from the harm of\n  aggregation, and recognize that public data can carry the\n  second without the first.\n- Identify causal language attached to associational evidence,\n  in your own writing and in the manuscripts you review.\n- Recognize the standard visual distortions: the truncated axis,\n  the area-for-quantity encoding, and the dual axis.\n- Demonstrate why overlapping confidence intervals do not imply\n  a non-significant difference, and stop making the inference.\n- Locate where in the workflow each of these failures is\n  introduced, and where it can be caught.\n\n## Orientation\n\nThe regulatory chapters of this book describe a floor. They\ntell you what you must not do: release identifiers, skip the\ndata-management plan, submit a dataset that fails conformance.\nClearing that floor is a necessary condition for defensible\npractice and it is nowhere near a sufficient one, because the\nfloor is written in terms of *procedures* and the failures that\nmatter most are failures of *inference*.\n\nFour such failures recur in biomedical work, and they have a\ncommon structure: at no point does anyone state a falsehood.\nThe data are real, the computation is correct, the p-value is\nwhat the software returned, the figure plots the numbers it\nclaims to plot. The misleading happens in the gap between what\nwas computed and what the reader concludes, and it is precisely\nin that gap that the statistician's professional obligation\nlives, because the statistician is the only person on the team\nwho can see the gap at all.\n\n## The statistician's contribution {#sec-ethics-human}\n\nThis chapter is judgement from beginning to end.\n\n**You are the last person who can catch this.** The clinical\ncollaborator cannot evaluate whether the confidence interval\nsupports the sentence in the abstract; that is why they have\nyou. The reviewer may or may not look. The reader certainly\nwill not. When the press release says 'exercise prevents\ncancer' and your analysis found an association in an\nobservational cohort of volunteers, you are not a bystander to\nthat sentence. You are its last opportunity.\n\n**Public is not the same as consented, and available is not the\nsame as ethical.** The question 'may I' has a legal answer and\nan ethical one, and they are different questions. A dataset\nthat violates no rule can still hurt the people in it. Ask what\nhappens to a person in your data if the analysis is right, and\nthen ask what happens if it is wrong.\n\n**Distortion is usually accidental, which does not make it\nharmless.** Almost nobody sets out to deceive with a truncated\naxis. They set out to make the effect visible, and a truncated\naxis makes it visible, and the reader who glances at the figure\ncarries away an impression the data do not support. Intent is\nnot the standard. The standard is what a competent reader would\nconclude.\n\n**Refusing is part of the job.** There is a point at which the\ncorrect professional act is to decline: to refuse to sign the\nmanuscript, to refuse to produce the figure as specified, to\nsay that the analysis as requested is not one you will perform.\n@sec-team-science distinguishes preference from principle\nprecisely so that you spend your credibility on the cases where\nthis matters. This chapter is the catalog of those cases.\n\n## Aggregation harm\n\nThe first failure concerns data that were never private.\n\nIn 2016 a group of researchers released a dataset of some\n70,000 profiles scraped from a dating website, including\nusernames alongside answers to intimate questions about\nsexuality, drug use, and political views. The defense offered\nwas that the data 'are already publicly available', which was\ntrue and beside the point. Each user had disclosed a fact to an\naudience of their choosing, in a context they understood. The\nrelease did something none of them had chosen: it collected\nthose disclosures into a single, searchable, permanent,\ndownloadable artifact, and attached them to identifiers.\n\nThis is **aggregation harm**, and it is the same phenomenon\nthat @sec-deident treats formally under the heading of\nquasi-identifiers, arriving from the other direction. There,\nthe point was that no single ordinary variable identifies\nanyone but their conjunction can. Here, the point is that no\nsingle disclosure harms anyone but their conjunction can. The\nmathematics is the mathematics of joint distributions; the\nethics is the ethics of context. Information carries with it an\nimplicit expectation about where it will travel, and moving it\nsomewhere else is an act with consequences even when every\nindividual datum was freely given.\n\nThe practical tests, before you assemble a dataset from public\nsources:\n\n- **Would the people in it be surprised?** Not 'would they\n  object', which invites you to answer for them, but 'would\n  they be surprised to find themselves in it'. Surprise is a\n  reliable signal that a contextual expectation is being\n  violated.\n- **Does the aggregate reveal what the parts did not?** Someone\n  who posted in a support forum has disclosed a health\n  condition to that forum. A dataset linking forum posts to\n  employer names has disclosed it to their employer.\n- **Can it be de-identified without destroying the analysis?**\n  If yes, do that (@sec-deident). If no, that is informative:\n  it means the identifiers are load-bearing, and you should be\n  able to say why.\n\n## Causal overclaiming\n\nThe second failure is the most common one in biomedical\npublishing, and it usually happens in the last paragraph.\n\nAn observational cohort of self-selected volunteers reports\nthat those who exercised more had lower cancer incidence,\nadjusting for age, sex, smoking, and body-mass index. The\nfinding is an association. The discussion section says the\nfinding 'suggests that exercise reduces cancer risk'. The press\noffice says exercise prevents cancer. The newspaper says it\ncures it. At no step did anyone fabricate a number.\n\nThe statistician's job is to insist that the verb match the\ndesign. The three registers, from @sec-team-science, are worth\nrestating as a hierarchy of claims:\n\n| Design | What you may say |\n|---|---|\n| Randomized, adequately powered, pre-specified | 'X reduced Y by $\\delta$' |\n| Observational, well adjusted, no unmeasured confounding assumed | 'X was associated with lower Y; the association is consistent with a causal effect but the design cannot establish one' |\n| Observational, self-selected sample, self-reported exposure | 'Among volunteers who reported X, Y was lower. Volunteers who exercise differ from those who do not in ways we did not measure.' |\n\nThe third row is the one to keep in view. The problem with a\nvolunteer cohort reporting its own exercise is not that the\nconfounder adjustment was inadequate. It is that people who\nexercise and report it differ systematically from people who do\nnot, along dimensions (conscientiousness, health-seeking\nbehavior, unmeasured comorbidity, the very early symptoms of\nundiagnosed disease) that no covariate list captures. The\nadjustment cannot fix this, and stating that you adjusted for\nage and smoking implies to a reader that it did.\n\nThe specific place this fails is the transition from Results to\nDiscussion, where the verb changes from 'was associated with'\nto 'reduces' without anyone noticing. Read your own discussion\nsection as a hostile reviewer, and grep for causal verbs:\nreduces, prevents, protects, causes, leads to, improves. Each\none is a claim your design must license.\n\n## Visual misrepresentation\n\nThe third failure needs no numbers at all, only their encoding.\nThe figure below plots the same two group means twice.\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(patchwork)\n\nd <- tibble(\n  arm  = c(\"Control\", \"Treatment\"),\n  mean = c(72.4, 74.1)\n)\n\nbase <- ggplot(d, aes(arm, mean, fill = arm)) +\n  geom_col(width = 0.6, show.legend = FALSE) +\n  scale_fill_manual(values = c(Control = \"#9d2235\",\n                               Treatment = \"#1f4e79\")) +\n  labs(x = NULL, y = \"Score\") +\n  theme_minimal()\n\np_honest    <- base +\n  coord_cartesian(ylim = c(0, 100)) +\n  labs(title = \"A. Axis from zero\")\n\np_truncated <- base +\n  coord_cartesian(ylim = c(71, 75)) +\n  labs(title = \"B. Axis from 71\")\n\np_honest + p_truncated\n```\n\n::: {.cell-output-display}\n![The same two means, encoded twice. Panel A begins the y-axis at zero and the difference is what it is: small. Panel B begins the axis at 71 and the same difference fills the panel. Neither panel contains a false number, and a reader who glances at B carries away a conclusion the data do not support.](02c-ethics_files/figure-html/fig-truncated-1.png){#fig-truncated fig-align='center' width=100%}\n:::\n:::\n\n\n\n\n\n\nThe difference is 1.7 points on a 100-point scale. Panel A\ntells you that. Panel B tells you that the treatment arm is\nroughly three times the control arm, which is false, and it\ntells you so without printing a single incorrect value.\n\nThe three standard distortions:\n\n**The truncated axis.** As above. The rule is not 'always start\nat zero', because for many quantities zero is meaningless (body\ntemperature, calendar year, pH) and forcing it wastes the panel.\nThe rule is that *when the visual encoding is length or area*,\nas in a bar chart, the baseline must be zero, because the\nreader is comparing lengths and a truncated bar's length is not\nproportional to its value. For a point-and-interval plot, where\nthe encoding is position rather than length, a truncated axis is\nlegitimate and often necessary. The question is always: what is\nthe reader's eye measuring?\n\n**Area for quantity.** A map colored by which arm won each\ncounty encodes *land area*, and land does not vote. A bubble\nwhose *radius* is proportional to a count exaggerates it, because\nthe eye reads area, which goes as the square of the radius. In\nbiomedicine the recurring case is a map of disease counts that\nis really a map of where people live, and the fix is a rate, a\ndenominator, and a cartogram or a population-weighted encoding.\n\n**The dual axis.** Two series on two differently scaled y-axes\ncan be made to cross, converge, or diverge at the analyst's\nchoice, because the relative scaling is arbitrary. Any apparent\nrelationship between them is an artifact of a decision you made.\nAvoid dual axes entirely; if two series must be compared, index\nthem to a common baseline or use two panels.\n\n## The overlapping-interval fallacy\n\nThe fourth failure is the one a biostatistician is most likely\nto commit personally, and it is a genuine technical error rather\nthan a rhetorical one.\n\nThe reasoning goes: the 95% confidence intervals for the two\ngroup means overlap, therefore the difference is not significant\nat the 5% level. This is wrong, and it is wrong in the direction\nof missing real effects. The interval for a *difference* depends\non the standard error of the difference, which is smaller than\nthe sum of the two individual standard errors, and intervals for\nthe two means can overlap substantially while the interval for\ntheir difference excludes zero.\n\nA demonstration, on synthetic data constructed to make the point\nsharply:\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(18)\n\na <- rnorm(60, mean = 100, sd = 12)\nb <- rnorm(60, mean = 105, sd = 12)\n\nci <- function(x) {\n  m  <- mean(x)\n  se <- sd(x) / sqrt(length(x))\n  c(lower = m - 1.96 * se, mean = m, upper = m + 1.96 * se)\n}\n\nrbind(group_a = ci(a), group_b = ci(b)) |> round(1)\n#>         lower  mean upper\n#> group_a  96.0  99.4 102.7\n#> group_b 101.7 104.3 106.9\n\nt.test(b, a)\n#> \n#> \tWelch Two Sample t-test\n#> \n#> data:  b and a\n#> t = 2.289, df = 111.36, p-value = 0.02397\n#> alternative hypothesis: true difference in means is not equal to 0\n#> 95 percent confidence interval:\n#>  0.6621209 9.1959712\n#> sample estimates:\n#> mean of x mean of y \n#> 104.28772  99.35868\n```\n:::\n\n\n\n\n\n\nThe two intervals overlap: group A reaches 102.7 and group B\nbegins at 101.7. The two-sample test nonetheless rejects at the\n5% level ($p = 0.02$). Anyone reading the overlap off a figure\nand concluding 'no significant difference' has reached the\nopposite conclusion from the one the data support.\n\nThe overlap here is about one point, which is deliberate: the\nfallacy does its damage in exactly this regime, where the\nintervals graze each other and the difference is real. As the\ndifference grows the intervals separate and the two readings\nagree; as it shrinks the test stops rejecting and they agree\nagain. It is the middle, where an analyst is most likely to be\nlooking for guidance from the figure, that the overlap heuristic\ngets wrong.\n\n@fig-overlap shows why. The correct object to look at is not\nthe pair of intervals but the interval for their difference,\nwhich is a different quantity and answers the question actually\nbeing asked.\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmeans <- bind_rows(\n  as_tibble_row(ci(a)) |> mutate(group = \"A\"),\n  as_tibble_row(ci(b)) |> mutate(group = \"B\")\n)\n\ntt <- t.test(b, a)\ndiff <- tibble(\n  group = \"B - A\",\n  mean  = unname(diff(rev(tt$estimate))),\n  lower = tt$conf.int[1],\n  upper = tt$conf.int[2]\n)\n\np_means <- ggplot(means, aes(mean, group)) +\n  geom_pointrange(aes(xmin = lower, xmax = upper)) +\n  labs(title = \"A. Group means\", x = \"Score\", y = NULL) +\n  theme_minimal()\n\np_diff <- ggplot(diff, aes(mean, group)) +\n  geom_pointrange(aes(xmin = lower, xmax = upper)) +\n  geom_vline(xintercept = 0, linetype = \"dashed\",\n             color = \"#9d2235\") +\n  labs(title = \"B. Difference\", x = \"Difference in score\",\n       y = NULL) +\n  theme_minimal()\n\np_means + p_diff\n```\n\n::: {.cell-output-display}\n![Left: the two group means with their 95% intervals, which overlap. Right: the 95% interval for the difference, which excludes zero. These are not in conflict; they are answers to different questions. Reading significance off the overlap on the left is the error.](02c-ethics_files/figure-html/fig-overlap-1.png){#fig-overlap fig-align='center' width=100%}\n:::\n:::\n\n\n\n\n\n\nThe practical consequences are two. When you *report*, give the\ninterval for the contrast, not merely intervals for the arms,\nbecause the contrast is the estimand. When you *review*, treat\nany sentence of the form 'the intervals overlapped, so the\ngroups did not differ' as an error, and say so.\n\n::: {.callout-note icon=false collapse=true}\n## Check your understanding: the compliant misleading paper\n\n**Question.** A paper reports an observational study. The IRB\napproved it, the data are properly de-identified under Safe\nHarbor, the DMSP is in place, the code is on Zenodo with a DOI,\nand every number in the paper is correctly computed from the\ndata. The abstract concludes that the intervention 'reduces\n30-day readmission'. Has anything gone wrong?\n\n**Answer.**\n\nYes, and nothing in the compliance apparatus was built to catch\nit. Every requirement in @sec-federal and @sec-deident is\nsatisfied, the analysis is reproducible in the sense of\n@sec-why, and the reported numbers are right. What is wrong is a\nverb: an observational design licenses 'was associated with\nlower readmission', not 'reduces'. The distinction is not\npedantry. A reader, a guideline committee, or a health system\ndeciding where to spend money will act on 'reduces', and the\nevidence does not support the action.\n\nNote what this implies about the rest of the book.\nReproducibility, compliance, and correctness of computation are\neach necessary and they are jointly insufficient: a perfectly\nreproducible, fully compliant, numerically correct analysis can\nstill mislead every reader it reaches. The tools cannot close\nthat gap. Only the analyst can.\n\n:::\n\n## Where each failure is caught\n\nThe four failures enter the workflow at different points, which\nmeans they are caught at different points.\n\n| Failure | Introduced at | Caught by |\n|---|---|---|\n| Aggregation harm | Data acquisition (@sec-acquisition) | Asking, before you assemble, whether the people in the data would be surprised |\n| Causal overclaiming | The Results-to-Discussion transition | Reading your own discussion for causal verbs; peer review (@sec-communicating) |\n| Visual misrepresentation | Figure construction (@sec-graphics) | Asking what the reader's eye is measuring |\n| Overlapping-interval fallacy | Interpretation, and often the figure | Reporting the contrast, not the arms |\n\nNone of them is caught by a test suite, a lockfile, or a\ncontainer. That is the point of the chapter, and it is worth\nstating plainly: the entire infrastructural apparatus of this\nbook is orthogonal to whether the analysis misleads.\nReproducibility guarantees that a wrong conclusion can be\nregenerated exactly.\n\n## Collaborating with an LLM on ethical review\n\nModels are useful here and dangerous in a specific way: they are\nagreeable, and every failure in this chapter is one an agreeable\ncollaborator would let pass.\n\n**Prompt 1: auditing your own discussion section.** Paste it and\nask: 'list every sentence whose verb implies causation, and for\neach, state what design would license it.'\n\n*What to watch for.* This works well, because it is a\ntext-classification task rather than a judgement. Expect a few\nfalse positives. The sentences it flags are the sentences a\nskeptical reviewer will flag.\n\n*Verification.* For each flagged sentence, check the design\nagainst the table in this chapter. If the design is\nobservational and the verb is causal, rewrite it.\n\n**Prompt 2: critiquing a figure.** Describe the encoding (bar\nchart, y-axis from 71 to 75, two groups) and ask what a reader\nwould wrongly conclude.\n\n*What to watch for.* The model will identify the truncated\nbaseline reliably. It is weaker on subtler distortions, such as\nan area encoding or an inappropriate denominator, because those\nrequire knowing what the quantity means.\n\n*Verification.* Render the figure both ways, as this chapter\ndoes, and look at them side by side. The comparison is more\npersuasive than any critique.\n\n**Prompt 3: the one it will get wrong.** Ask it whether you may\nrelease a dataset assembled from public profiles.\n\n*What to watch for.* The model is likely to reason from\nlegality, because legality is what is written down, and to\nconclude that public data may be republished. Push it: ask what\nharm a person in the dataset could suffer, and ask whether they\nwould be surprised. The considerations exist in its training\ndata but it will not volunteer them, and this is exactly the\nterritory where an agreeable collaborator is worse than none.\n\n*Verification.* Take the question to your IRB, and to a\ncolleague who will tell you no.\n\n## Principle in use\n\nIn closing, three habits define what we would regard as defensible practice beyond compliance:\n\n1. **Match the verb to the design.** Observational studies\n   license association. If the discussion section says\n   'reduces', the design had better be randomized.\n2. **Ask what the reader's eye is measuring.** A bar encodes\n   length, so its baseline is zero. A map encodes area, and land\n   does not have a disease. A dual axis encodes an arbitrary\n   choice you made.\n3. **Compliance is a floor, not a ceiling.** Every regulatory\n   requirement in this book can be satisfied by an analysis that\n   misleads every reader it reaches. You are the only safeguard\n   against that, and it is the part of the job no tool performs.\n\n## Exercises\n\n1. Take the discussion section of a paper you have co-authored.\n   List every causal verb. For each, state the design that would\n   license it and the design you actually had. Rewrite any that\n   fail.\n2. Reproduce the truncated-axis figure in this chapter with data\n   of your own. Show it to a colleague without comment and ask\n   them to describe the effect size in words. Then show them the\n   zero-baseline version and ask again.\n3. Construct a dataset in which two group means have overlapping\n   95% intervals and a two-sample t-test rejects at the 5%\n   level. State the largest overlap you can achieve while\n   retaining significance, and explain the relationship between\n   the standard error of a mean and the standard error of a\n   difference.\n4. Find a published figure in your field that encodes a quantity\n   as area or uses a dual axis. Redraw it honestly. Write a\n   paragraph on what changes.\n5. Write a one-page policy, suitable for a research group, on\n   when data assembled from public sources may be released.\n   Include the questions you would require an analyst to answer\n   before assembling such a dataset.\n\n## Further reading\n\n- [@altman1995absence], on the specific inferential error that\n  the overlapping-interval fallacy is a cousin of.\n- [@wilke2019fundamentals], whose chapters on misleading axes\n  and on visualizing uncertainty are the extended treatment of\n  this chapter's third and fourth sections.\n- [@elemam2013anonymizing], for the disclosure-control side of\n  the aggregation problem.\n- [@goodman2016what], for the reminder that reproducibility and\n  correctness are independent qualities.\n- @sec-deident, @sec-federal, and @sec-graphics, the chapters\n  this one sits between.\n\n## Prerequisites answers {#sec-quiz-answers-02c}\n\n1. Because the harm of aggregation differs from the harm of\n   disclosure. Each individual disclosed a fact to an audience of\n   their choosing, in a context they understood; assembling those\n   disclosures into a single searchable, permanent, downloadable\n   artifact and attaching identifiers to it does something none\n   of them chose. Information carries an implicit expectation\n   about where it will travel, and the aggregate can reveal what\n   no individual datum did, for example by linking a health\n   disclosure in one forum to an employer named in another. This\n   is the same joint-distribution phenomenon that makes\n   quasi-identifiers dangerous in @sec-deident, arriving from the\n   other direction. The test is not 'was each item public' but\n   'would the people in the dataset be surprised to find\n   themselves in it'.\n2. No. This is a common and consequential error. The confidence\n   interval for the *difference* depends on the standard error of\n   the difference, which is smaller than the sum of the two\n   individual standard errors, so two means can have substantially\n   overlapping intervals while the interval for their difference\n   excludes zero and the two-sample test rejects. The chapter\n   demonstrates exactly this case. The error runs in the direction\n   of missing real effects. Report and inspect the interval for\n   the contrast, which is the estimand, rather than reading\n   significance off the overlap of the arms.\n3. (Any three of:) a truncated axis on a length-encoded chart, so\n   that a 1.7-point difference on a 100-point scale fills the\n   panel; encoding a quantity as area, including a map colored by\n   land rather than by population, or a bubble whose radius rather\n   than area is proportional to the count; a dual axis, whose\n   relative scaling is an arbitrary analyst choice that can be\n   tuned to make two series appear to converge or diverge;\n   omitting the uncertainty entirely, so that a point estimate\n   invites more confidence than it has earned; and choosing a\n   denominator that flatters the conclusion. None of these\n   requires printing a false number.\n",
    "supporting": [
      "02c-ethics_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}