{
  "hash": "ca7490f24206c5c0ddb87a4248cefa78",
  "result": {
    "engine": "knitr",
    "markdown": "# Communicating a Finished Analysis {#sec-communicating}\n\n::: {.bookepigraph}\n```{=latex}\n\\begin{flushright}\\small\n```\n*The single biggest problem in communication is the illusion\nthat it has taken place.*\n\n[William H. Whyte]{.smallcaps}, *Is Anybody Listening?* (1950)\n```{=latex}\n\\end{flushright}\n```\n:::\n\n::: {.callout-note}\n## Why this chapter exists\n\nThe book has taught the reader to produce a defensible\nanalysis and has stopped there. @sec-team-science covers the\nregister in which a statistician should speak to a clinician,\nand @sec-graphics covers the figure, but neither addresses the\nartifact the reader will actually be judged on. A working\nbiostatistician delivers findings in three forms, and writes\nsome of them weekly: the talk, the memo, and the response to\nreviewers. A book that devotes a chapter to SAS on grounds of\nemployability cannot reasonably be silent about the three\ndocuments that constitute the job.\n:::\n\n## Prerequisites\n\nAnswer the following questions to see if you can bypass this\nchapter. You can find the answers at the end of the chapter in\n@sec-quiz-answers-25b.\n\n1. Why is the order in which you conducted an analysis almost\n   never the right order in which to present it?\n2. Your primary analysis found no effect. What, precisely, is\n   the difference between reporting that as 'no evidence of an\n   effect' and as 'evidence of no effect', and which one are\n   you usually entitled to?\n3. A reviewer asks you to re-run the primary analysis with a\n   different exclusion criterion. What in your compendium\n   determines whether that costs you an hour or a week?\n\n## Learning objectives\n\nBy the end of this chapter you should be able to:\n\n- Structure a set of findings as an argument rather than as a\n  chronology, using the and/but/therefore skeleton.\n- Give a twenty-minute talk to a clinical audience that leads\n  with the conclusion and defends it afterward.\n- Write a one-page memo to a principal investigator that a\n  busy reader can act on in four minutes.\n- Write a point-by-point response to reviewers that concedes\n  what should be conceded and defends what should be defended,\n  on technical grounds.\n- Report a null result without either apologizing for it or\n  overclaiming it.\n- Give and receive structured peer review on an analysis.\n\n## Orientation\n\nAn analysis is a chronology: you obtained the data, cleaned\nit, described it, modeled it, checked the model, and arrived\nat an estimate. That chronology is the right order for doing\nthe work, for the compendium, and for the methods section. It\nis the wrong order for almost every act of communication. It\nwithholds the thing the audience came for until the end, and\nasks them to hold six irrelevant facts in memory on the\npromise that the payoff is coming.\n\nPresenting an analysis is not narration. It is argument: here\nis the claim, here is the evidence, here is what would have\nchanged my mind. The three genres in this chapter are three\naudiences for that argument, differing in how much of the\nevidence they want and how much of the argument they will\ntolerate being told. The talk gets the least evidence and the\nmost argument; the response to reviewers gets the most\nevidence and the least latitude.\n\n## The statistician's contribution {#sec-communicating-human}\n\nEverything in this chapter is judgment; there is no tool.\n\n**Lead with the answer.** The clinical collaborator has one\nquestion, and it is the one they asked you three months ago.\nAnswer it in the first sentence, then defend the answer.\nStatisticians resist this, because the defense is where the\nwork was and the answer feels unearned without it. The\naudience does not share that feeling. They experience a\nwithheld conclusion as evasion, and their attention is spent\nbefore you reach it.\n\n**Calibrate the claim to the evidence, in both directions.**\nOverclaiming is the familiar sin, and the more common one. The\nopposite failure is real and is a particular affliction of the\ncareful: a hedge so complete that the reader cannot tell what\nyou found, and therefore substitutes their own prior. If the\nconfidence interval excludes any clinically meaningful effect,\nsay so plainly. If it does not, say that plainly too. The\nverbs matter here. 'We found X', 'the data are consistent with\nX', and 'we cannot rule out X' are three different claims, and\ntelling them apart, the discipline of @sec-team-science, is\nthe whole of the skill.\n\n**Decide what the audience should do differently.** Every\ncommunication has an implicit request: fund this, publish\nthis, stop this, change the protocol, collect more data,\nbelieve nothing yet. If you cannot state the request, you are\nnot yet ready to write. A memo that ends without one is a\nmemo the PI files and forgets.\n\n**Do not let the reviewer set the statistics.** A reviewer who\nasks for a subgroup analysis is asking for something that,\nperformed as asked, is exploratory and uncalibrated\n(@sec-analysis-plan). You should do it, report it, and label\nit. What you must not do is quietly promote it into the\nconfirmatory frame because a reviewer requested it. The\nrequest does not launder the inference, and the response\nletter is where you say so, politely and once.\n\nThese judgments are what distinguish a statistician who is\nconsulted again from one who is merely correct.\n\n## The narrative arc\n\nThe most portable structure for a scientific argument has\nthree parts, and it is easier to remember as a skeleton of\nconjunctions than as a diagram.\n\n**And.** The stable state of the world, which the audience\nalready accepts. 'Patients hospitalized with heart failure\nhave a thirty-day readmission rate of about twenty-five per\ncent, and post-discharge home-health visits are widely\nbelieved to reduce it.'\n\n**But.** The disruption. The reason the work exists. 'But the\nbelief rests on observational studies in which the patients\nwho received visits were systematically healthier than those\nwho did not.'\n\n**Therefore.** The response, and the finding. 'Therefore we\nrandomized 1,500 patients, and we find that home-health visits\nreduce thirty-day readmission by 4.2 percentage points, with a\nconfidence interval from 1.1 to 7.3.'\n\nThree sentences, and the audience now knows what you did, why,\nand what you found. Everything else in the talk or the memo is\nsupport for the third sentence. @tbl-arc contrasts the\nstructure with the chronology it replaces.\n\n| Chronology (the order you worked) | Argument (the order you present) |\n|---|---|\n| obtain data | **And**: the accepted background |\n| clean | **But**: why the work exists |\n| describe | **Therefore**: the estimate, stated first |\n| model | the defense: design, model, diagnostics |\n| diagnose | what would change my mind |\n| estimate | |\n\n: The chronology is the order in which the work was done, and the order the methods section follows. The argument is the order in which it should be presented. The estimate is the last thing computed and the first thing said; the chronology becomes the defense rather than the narrative. {#tbl-arc}\n\nThe final element of the argument is the one statisticians\nmost often omit and the one that most raises a skeptical\naudience's trust: state what would have changed your mind. 'If\nthe sensitivity analysis under a plausible MNAR mechanism had\nmoved the estimate below one percentage point, I would not be\npresenting this.' A speaker who volunteers the conditions\nunder which they would have been wrong is a speaker worth\nbelieving.\n\n## The talk\n\nTwenty minutes, a clinical audience, most of whom will not\nremember a number.\n\n**The first two minutes carry the talk.** Deliver the arc\nabove. If the audience leaves after two minutes they should\nhave the finding. Everything after is for those who want to\nknow whether to believe it.\n\n**One idea per slide, and the idea is the title.** A slide\ntitled 'Results' says nothing. A slide titled 'Home-health\nvisits reduced readmission by 4.2 points' says the thing, and\nthe figure beneath it is the evidence for the title. If a\nlistener reads only the titles, they should get the argument.\n\n**Show the estimate with its uncertainty, once, and large.**\nThe coefficient plot of @sec-graphics, with the interval, is\nthe single most important object in the talk. Do not bury it\nin a regression table, and do not show a regression table at\nall unless someone asks.\n\n**Anticipate the three questions.** For any clinical analysis\nthey are, reliably: how did you handle the patients who\ndropped out, could this be confounding, and does it hold in\nthe subgroup I care about. Have a backup slide for each. A\nbackup slide answered in ten seconds does more for your\ncredibility than the entire prepared talk.\n\n**Do not show code.** Ever, in this genre. The compendium is\nwhere the code lives, and the audience is not there to audit\nit. A single line naming the repository and the DOI, at the\nend, discharges the obligation.\n\n## The memo\n\nOne page, to a principal investigator, usually in response to\n'what did you find?' or 'is this worth pursuing?'.\n\nThe memo has a fixed shape, and its virtue is that the reader\ncan stop at any point and still have something usable.\n\n1. **The finding, in one sentence, with the number and its\n   interval.** No preamble.\n2. **The request.** What you want the reader to do. Approve\n   the manuscript, drop the arm, collect more data, stop.\n3. **The three things they should know.** The design in one\n   line, the estimate in one line, the principal threat to it\n   in one line.\n4. **The caveats, ranked.** Not an exhaustive list. The two or\n   three that could actually change the conclusion, in\n   descending order of how much they could change it.\n5. **What you propose to do next, with a time cost.**\n\nThe discipline is subtractive. Anything that does not survive\nthe question 'would the PI act differently if they knew this?'\ncomes out. Most methods detail comes out. The model\nspecification comes out. Diagnostics come out. They live in\nthe compendium, and the memo says where.\n\n### The numbers in a memo should be computed\n\nBefore the example itself, one point about how it is built.\nEvery figure quoted below is produced by the chunk that\nfollows and inserted by inline code, not typed. That is habit\nsix of @sec-synthesis applied to the one document where it is\nmost often skipped, because a memo feels like correspondence\nrather than output.\n\nThe reason to bother is that memos get revised. A data\ncorrection arrives, the analysis is rerun, and the prose still\ncarries last week's estimate unless a human remembers every\nplace a number appears. Inline code makes that\nimpossible: the number in the sentence *is* the number from\nthe model.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(dplyr)\n\n# The trial as reported: 1:1 randomization, readmission\n# ascertained from a state health-information exchange.\nn_arm <- 1353\n\ntrial <- tibble(\n  # a factor, so the arms keep trial order rather than\n  # alphabetical order when grouped\n  arm     = factor(rep(c(\"Usual care\", \"Home health\"), each = n_arm),\n                   levels = c(\"Usual care\", \"Home health\")),\n  readmit = c(rep(1L, 336), rep(0L, n_arm - 336),    # usual care\n              rep(1L, 279), rep(0L, n_arm - 279))    # home health\n)\n\nrates <- trial |>\n  group_by(arm) |>\n  summarize(n = n(), events = sum(readmit),\n            rate = mean(readmit), .groups = \"drop\")\n\n# prop.test takes control first, so the difference and the\n# interval are both usual care minus home health\nfit  <- prop.test(x = rates$events, n = rates$n, correct = FALSE)\ndiff <- 100 * (rates$rate[1] - rates$rate[2])\nci   <- 100 * fit$conf.int\n\nrates\n#> # A tibble: 2 × 4\n#>   arm             n events  rate\n#>   <fct>       <int>  <int> <dbl>\n#> 1 Usual care   1353    336 0.248\n#> 2 Home health  1353    279 0.206\nround(c(estimate = diff, lower = ci[1], upper = ci[2]), 1)\n#> estimate    lower    upper \n#>      4.2      1.1      7.4\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Pre-specified MNAR sensitivity. 6.3% of outcomes were not\n# ascertainable. The concern is one-sided: if the intervention\n# arm's unascertained patients fared worse than their observed\n# peers, the effect shrinks. So apply the penalty there only.\np_missing <- 0.063\ndelta     <- 1.5          # intervention arm's missing, relative risk\n\nadjusted <- rates |>\n  mutate(\n    n_miss   = round(n * p_missing),\n    penalty  = c(1, delta),                 # usual care, home health\n    ev_adj   = events + round(n_miss * rate * penalty),\n    rate_adj = ev_adj / n\n  )\n\nfit_s  <- prop.test(x = adjusted$ev_adj, n = adjusted$n,\n                    correct = FALSE)\ndiff_s <- 100 * (adjusted$rate_adj[1] - adjusted$rate_adj[2])\nci_s   <- 100 * fit_s$conf.int\n\nround(c(estimate = diff_s, lower = ci_s[1], upper = ci_s[2]), 1)\n#> estimate    lower    upper \n#>      3.8      0.6      7.1\n```\n:::\n\n\nNote what the second chunk establishes and what it does not.\nIt shows the conclusion survives one specific departure from\nthe missing-at-random assumption. It says nothing about\nwhether a factor of 1.5 is the right departure to worry\nabout, which is a clinical judgment the memo has to state in\nwords.\n\n### Worked example: a memo\n\n> **To:** Dr. X, Cardiology\n> **From:** A. Statistician\n> **Re:** HF-HOME primary analysis, 2026-06-15\n>\n> **Finding.** Home-health visits within seven days of\n> discharge reduced thirty-day all-cause readmission by\n> 4.2 percentage points (95% CI\n> 1.1 to 7.4;\n> from 24.8% to\n> 20.6%).\n> The pre-specified primary analysis supports the trial's\n> hypothesis.\n>\n> **Request.** Approval to proceed to manuscript, targeting\n> submission in six weeks.\n>\n> **What you should know.**\n>\n> - Design: 2,706 patients,\n>   1:1 randomized, stratified by site and baseline ejection\n>   fraction. The analysis is the one pre-specified in SAP\n>   v1.0, tagged before unblinding.\n> - Estimate: the interval excludes zero but includes effects\n>   as small as 1.1 points. The trial\n>   was powered to detect 4.5, so we are estimating an effect\n>   at roughly the size we planned for, with the imprecision\n>   that implies.\n> - Principal threat: 6.3% of\n>   patients had no outcome ascertainable from the state\n>   health-information exchange. These are handled by multiple\n>   imputation, and the pre-specified MNAR sensitivity analysis\n>   moves the estimate to 3.8 points\n>   (CI 0.6 to\n>   7.1). The conclusion is\n>   directionally robust but the lower bound is close to zero.\n>\n> **Caveats, ranked.**\n>\n> 1. The missing outcomes above. If patients lost to the\n>    exchange were readmitted at a substantially higher rate\n>    than those retained, the effect could fall below clinical\n>    relevance. I do not think this is likely, because loss to\n>    the exchange is driven by out-of-state address rather\n>    than by illness, but it is the assumption the result\n>    rests on and the manuscript must say so.\n> 2. Open-label design. Readmission is a hard endpoint and\n>    unlikely to be influenced by knowledge of arm, but the\n>    decision to admit is a clinician's judgment and is not\n>    fully hard.\n> 3. Single health system. External validity is unaddressed.\n>\n> **Next.** Draft methods and results in two weeks. I propose\n> adding the tipping-point analysis for the missing outcomes\n> (roughly one day) because a reviewer will ask for it and it\n> is cheaper to have it than to be asked.\n\nNotice what the memo does not contain: the model formula, the\ncovariate list, the diagnostics, the Table 1, the software\nversions. It contains a pointer to the compendium, where all\nof that lives, and it contains every fact on which the PI's\ndecision turns. It is also honest in a specific way that\nmatters: it volunteers that the lower bound is close to zero\nand that the sensitivity analysis erodes the estimate. A PI\nwho learns that from a reviewer instead of from you will not\ntrust the next memo.\n\n::: {.callout-note icon=false collapse=true}\n## Check your understanding: the number that changed\n\n**Question.** You sent a memo three weeks ago quoting a\nhazard ratio of 0.71. Rerunning after a data correction\ngives 0.78, which does not change the conclusion. Do you\ntell the PI, and what do you send?\n\n**Answer.**\n\nYes, and promptly, and the reasoning is not about the\nnumber.\n\nThe temptation to stay quiet is strongest exactly here,\nbecause the conclusion held. Saying nothing feels like\nsparing everyone a distraction over a difference that\ndoes not matter.\n\nIt matters for three reasons. The figure is already in\ncirculation: it may be in a slide deck, a draft, or a\ngrant, and every downstream use of 0.71 is now wrong even\nthough the conclusion is not. Second, someone else will\nfind it, and a discrepancy discovered by a reviewer costs\nfar more than one you reported. Third, and most\nconsequential, you are establishing what your silence\nmeans. A collaborator who learns that you report changes\nonly when they alter conclusions must independently verify\neverything, because your not-mentioning carries no\ninformation.\n\nWhat you send is short: the old number, the new number,\nwhat changed in the data, and one sentence stating the\nconclusion is unaffected. Not an apology, and not a\nrehearsal of the whole analysis. The compendium already\nholds the detail, and this is exactly what the version\nhistory is for; you can say precisely which commit\nproduced which number.\n\nThe general rule this chapter is built on: your value to a\nteam is that your numbers can be relied upon, which\ndepends far more on how you handle the ones that change\nthan on the ones that do not.\n:::\n\n## Null results\n\nThe analysis found nothing. This happens constantly, and the\nhandling of it separates careful statisticians from the rest.\n\nThe first distinction is the one in this chapter's quiz.\n**Absence of evidence is not evidence of absence.** A wide\nconfidence interval that includes zero means you could not\ndistinguish the effect from nothing; it does not mean the\neffect is nothing. The claim you are entitled to is 'we found\nno evidence that X', not 'we found that X does not work'. The\nsecond claim requires an interval narrow enough to exclude any\neffect you would have cared about, and you should say so\nexplicitly when you have it:\n\n> The confidence interval (from -0.4 to 0.6 percentage points)\n> excludes the 2-point difference the trial was designed to\n> detect and, indeed, excludes any difference we would regard\n> as clinically meaningful. This is not an inconclusive\n> result; it is a reasonably precise null.\n\nThat is a strong scientific statement and a publishable one.\nContrast it with the same data described as 'the difference\nwas not statistically significant (p = 0.72)', which tells the\nreader nothing about whether the study was informative.\n\nThe second distinction is between a null result and a failed\nstudy. A trial that enrolled half its target and produced an\ninterval spanning every effect from harmful to miraculous has\nnot produced a null result; it has produced no result, and the\nhonest report says so. Presenting an underpowered null as\nevidence of no effect is one of the more consequential forms\nof misreporting in the clinical literature, and the\nstatistician is the only person on the team positioned to stop\nit.\n\n::: {.callout-note icon=false collapse=true}\n## Check your understanding: what may you claim?\n\n**Question.** Your trial estimates a treatment effect of 0.3\npercentage points with a 95% confidence interval from -3.9 to\n4.5. The minimum clinically important difference agreed at the\noutset was 2 points. The PI would like to write 'the\nintervention was not effective'. What do you say?\n\n**Answer.**\n\nYou say that the sentence is not supported. The interval\nincludes effects as large as 4.5 points, more than twice the\nminimum clinically important difference, so the data are\nentirely consistent with a clinically important benefit. They\nare also consistent with a clinically important harm. The\nstudy did not distinguish these possibilities, and the correct\nreport is that it was uninformative about effects in the range\nthat matters: 'we found no evidence of an effect, but the\nstudy cannot exclude a clinically important benefit or harm'.\n\nThe sentence the PI wants would be defensible only if the\ninterval lay wholly inside the region of clinical\nindifference, for example from -1.2 to 1.4, which excludes the\n2-point difference on both sides. Then, and only then, 'the\nintervention was not effective at any clinically meaningful\nmagnitude' is a claim the data support. The distinction is\nbetween a precise null and an inconclusive one, and conflating\nthem is how the literature acquires its 'negative' trials that\nwere merely small.\n\n:::\n\n## The response to reviewers\n\nThe manuscript comes back with three reviewers and eleven\ncomments, of which five are statistical and land on you. The\nresponse letter is its own genre and follows strict\nconventions.\n\n**Quote every comment, respond to every comment, in order.**\nNumber them. Reproduce the reviewer's text verbatim, in a\ndistinguishable typeface, and place your response beneath it.\nAn editor reading the letter must be able to verify, without\ncross-referencing, that nothing was ignored. Silence on a\ncomment reads as evasion even when it was an oversight.\n\n**Say what changed and where.** 'We have added the requested\nsensitivity analysis (Methods, p. 8; Supplementary Table S6;\nFigure 3 revised).' A response that agrees with a point but\ndoes not say where the manuscript now reflects it forces the\neditor to hunt, and irritating the editor is a strictly\ndominated strategy.\n\n**Concede quickly what should be conceded.** If the reviewer\nis right, say so in one sentence, make the change, and move\non. Defensive paragraphs attached to a concession make the\nconcession look grudging and invite scrutiny of the rest.\n\n**Disagree on technical grounds, once, and without heat.**\nWhen the reviewer is wrong, the response states the technical\nreason, offers the analysis that demonstrates it, and stops.\nIt does not restate the point three ways, and it does not\nimply that the reviewer has failed to read the paper, even\nwhen they plainly have not.\n\n**Do not let a request change the inferential status of an\nanalysis.** This is the statistical judgment at the center of\nthe genre. When a reviewer asks for a subgroup analysis, they\nare asking for an analysis that was not pre-specified. Perform\nit, report it, and label it exploratory. The temptation, and\nit is a real one because the reviewer holds the decision, is\nto fold it into the results as though it had been planned. It\nwas not, and doing so is precisely the practice\n@sec-analysis-plan exists to prevent.\n\n### Worked example: three responses\n\n> **Comment 1.3.** *'The authors should report a sensitivity\n> analysis to the missing outcome data, which at 6.3% is not\n> negligible.'*\n>\n> We agree, and we thank the reviewer. A delta-adjustment\n> sensitivity analysis under a plausible MNAR mechanism was\n> pre-specified in SAP v1.0 but, on review, was reported only\n> in the supplement. We have moved it into the main text\n> (Results, p. 12) and added a tipping-point analysis\n> (Supplementary Figure S4). The conclusion is unchanged: the\n> effect estimate falls from 4.2 to 3.6 points, and the\n> interval continues to exclude zero until the imputed\n> outcomes are shifted by more than 1.4 standard deviations,\n> a magnitude we regard as implausible given that loss to\n> follow-up was driven by out-of-state address rather than by\n> clinical status.\n>\n> **Comment 2.1.** *'The effect appears larger in patients\n> with reduced ejection fraction. The authors should present\n> this subgroup as a primary finding, as it is likely the\n> mechanism.'*\n>\n> We have added the subgroup analysis (Supplementary Table\n> S7), which does show a larger point estimate in the reduced-\n> ejection-fraction stratum (5.8 vs 3.1 points), with an\n> interaction test that is not significant (p = 0.31). We\n> respectfully decline to present it as a primary finding, for\n> two reasons. First, it was not pre-specified: the analysis\n> plan (deposited at ClinicalTrials.gov before unblinding,\n> and cited in the Methods) names a single primary analysis in\n> the full randomized population, and promoting a subgroup\n> selected after the data were seen would render its nominal\n> error rate uninterpretable. Second, the trial was not\n> powered for interaction, and an apparent difference of this\n> magnitude between strata is well within what sampling\n> variation produces under a common true effect. We now\n> report the subgroup as exploratory and hypothesis-generating\n> (Results, p. 14; Discussion, p. 19), and we note it as a\n> candidate for prospective testing.\n>\n> **Comment 3.2.** *'A logistic regression is inappropriate\n> here; the authors should have used a Cox model.'*\n>\n> The outcome is binary readmission within a fixed 30-day\n> window, ascertained for all patients, and every patient was\n> followed for the full window or had their outcome\n> ascertained through linkage. There is therefore no censoring\n> to accommodate, and the estimand of interest is a risk\n> difference over a fixed horizon rather than a hazard ratio.\n> A Cox model would answer a different question and would\n> require an assumption (proportional hazards) that the design\n> does not need. We have added a sentence to the Methods\n> (p. 7) making the estimand explicit, which we hope clarifies\n> the choice.\n\nThree comments, three different postures: agree and fix, agree\nto perform but decline to reframe, and disagree on technical\ngrounds. None of the three is defensive, and all three tell\nthe editor exactly where in the manuscript to look.\n\nObserve also what made the first response cheap to write. The\nsensitivity analysis existed, because the SAP pre-specified\nit; the tipping-point analysis took a day, because the\ncompendium rebuilds with one command; and the claim that the\nplan predates unblinding is verifiable, because the SAP was\ntagged in Git (@sec-analysis-plan) and deposited at the\nregistry. The infrastructure chapters of this book pay their\nreturn here, at the moment when a reviewer asks a question six\nmonths after you last thought about the analysis.\n\n## Peer review as a practice\n\nThe skills above are trained by performing review, not by\nreceiving it. A reviewer who has had to articulate why an\nanalysis is unconvincing writes more convincing analyses.\n\nWhen reviewing a colleague's analysis, the questions worth\nasking, roughly in the order that catches the most:\n\n- What is the claim, and can I find it stated in one sentence?\n- Does the reported estimate come with an interval, and is the\n  interval interpreted rather than merely printed?\n- Is the primary analysis the one that was pre-specified, and\n  can I verify that from the artifact rather than the prose?\n- What is the denominator, and does it match the flow diagram?\n- Which single assumption, if wrong, would most change the\n  conclusion, and does the paper name it?\n- Would I be able to re-run this?\n\nThat list is short by design, and it is the list of a\ngeneralist reader. For the statistical content specifically,\nthe most compact published instrument is Harrell's author\nchecklist [@harrell2024checklist]. It enumerates the errors a\nbiomedical manuscript makes often enough to be worth checking\nmechanically: exact p-values rather than 'NS' or 'p < 0.05',\nintervals reported alongside tests, continuous variables not\ncategorized, no stepwise selection, missingness documented\nrather than silently dropped, deviations from the analysis plan\nstated as deviations, and figures that show the data rather\nthan a bar whose height is a mean. Run it against your own\ndraft before you send it out; that is cheaper than having a\nreviewer run it for you. Run it as well against a colleague's\ndraft when you are the reviewer. The overlap with\n@sec-analysis-plan is\nnot accidental: most of the checklist's items are failures of\npre-specification arriving late enough to be expensive.\n\nWhen receiving review, the discipline is to separate the\ncomment from its tone. A reviewer who is rude and right has\nstill handed you a free defect report. The response letter is\nnot the place to relitigate the tone, and the mildest possible\nversion of the disagreement is invariably the most effective.\n\n## Collaborating with an LLM on communication\n\nLanguage models write fluent prose and are correspondingly\ndangerous here, because fluency in this genre is often the\nvehicle for an overclaim.\n\n**Prompt 1: drafting the memo.** Paste the estimate, the\ninterval, the design, and the sensitivity results, and ask for\na one-page memo in the structure of this chapter.\n\n*What to watch for.* Calibration. The model will reach for\n'significant', 'demonstrates', and 'confirms' where the\nevidence supports 'is consistent with'. It will also tend to\nsoften or omit the caveat that hurts. Read the draft asking\none question: does any sentence claim more than the interval\npermits?\n\n*Verification.* Take each sentence containing a claim and\ncheck it against the confidence interval. Then hand the memo\nto a colleague and ask them what you found and what you want\nthem to do. If they cannot say, the memo has failed\nregardless of how well it reads.\n\n**Prompt 2: drafting the response to reviewers.** Paste the\nreviewer's comment and your position, and ask for a response.\n\n*What to watch for.* Two failure modes, in opposite\ndirections. The model is agreeable by disposition and will\nconcede points it should defend, including, characteristically,\nagreeing to promote an exploratory subgroup analysis because\nthe reviewer asked. It also occasionally produces a defensive\nparagraph where one sentence would do. You supply the posture;\nthe model supplies the prose.\n\n*Verification.* For every conceded point, ask whether you\nactually agree. For every defended point, check that the\ndefense is technical rather than rhetorical.\n\n**Prompt 3: adversarial review of your own draft.** Paste the\nresults section and ask the model to review it as a hostile\nstatistical reviewer, listing every claim not supported by the\nreported evidence.\n\n*What to watch for.* This is the most valuable of the three\nprompts, because the model is better at finding overclaims in\ntext than at avoiding them in its own. Expect a mix of real\nfindings and pedantry; the real findings are worth the sort.\n\n*Verification.* Each flagged claim is a hypothesis about a\nweakness. Check it against the analysis. The ones that survive\nare the comments a real reviewer will make, and you now have\nsix weeks rather than six days to address them.\n\n## Principle in use\n\nThree habits decide whether the analysis reaches the reader\nintact:\n\n1. **Lead with the answer, then defend it.** The chronology of\n   the analysis is the order you worked, not the order anyone\n   should hear.\n2. **Match the claim to the interval, in both directions.** No\n   evidence of an effect is not evidence of no effect, and a\n   precise null is a real finding that deserves to be stated\n   as one.\n3. **Never let a request change an analysis's inferential\n   status.** A reviewer may ask for the subgroup. They cannot\n   make it confirmatory.\n\n## Exercises\n\n**On your own machine, data, or collaborations.** These exercises\nproduce documents and conversations, so no answer key is possible. What\na good answer establishes is stated with each.\n\n1. Take the last analysis you completed and write its and/but/\n   therefore in three sentences. If the 'but' is difficult to\n   write, ask yourself why the analysis was performed.\n2. Write the one-page memo for that analysis, following the\n   five-part structure in this chapter. Give it to a colleague\n   who does not know the project and ask them, without\n   prompting, what you found and what you want them to do.\n   Revise until they can answer both.\n3. Take a published paper reporting a null result. Determine\n   from the reported interval whether it is a precise null or\n   an inconclusive one, and then check what the abstract\n   claims. Write a paragraph on the gap, if any.\n4. Find a set of published reviewer comments and author\n   responses (many journals now publish them). Identify one\n   response that concedes what it should have defended, or\n   defends what it should have conceded, and rewrite it.\n5. Review a colleague's analysis against the six questions in\n   the peer-review section. Deliver the review in writing.\n   Then ask them which comment was most useful, and why; it is\n   rarely the one you expected.\n\n## Further reading\n\n- [@slade2023team], on the communication skills that\n  interdisciplinary team science demands of statisticians.\n- [@wilke2019fundamentals], whose closing chapters on telling\n  a story with figures are the visual counterpart to the\n  narrative arc taught here.\n- [@altman1995absence], the two-page paper this chapter's\n  null-results section restates at greater length.\n- [@icmje2024], for the conventions governing what a\n  manuscript and its correspondence must contain.\n- [@harrell2024checklist], the author checklist used\n  in the peer-review section above.\n- [@schulz2010consort] and [@vonelm2007strobe], the\n  reporting standards that determine what your results\n  section is obliged to state.\n- @sec-analysis-plan and @sec-git-solo, the infrastructure\n  that makes a response to reviewers cheap rather than\n  ruinous.\n\n## Prerequisites answers {#sec-quiz-answers-25b}\n\n1. Because the chronology withholds the conclusion until the\n   end and asks the audience to retain the preliminaries on\n   the promise of a payoff they cannot yet evaluate. An\n   audience wants the claim first and the evidence second, so\n   that they know what the evidence is evidence *for*. The\n   chronology remains the right order for the methods section\n   and for the compendium, where the reader's purpose is\n   verification rather than comprehension. For a talk or a\n   memo, structure the material as an argument: the accepted\n   state of the world, the disruption that motivated the work,\n   the finding, the defense, and the conditions under which\n   you would have concluded otherwise.\n2. 'No evidence of an effect' says that the study could not\n   distinguish the effect from zero, which is a statement\n   about the study's resolution. 'Evidence of no effect' says\n   that the effect is absent, or at least too small to matter,\n   which is a statement about the world. You are entitled to\n   the second only when the confidence interval excludes every\n   effect you would have regarded as clinically meaningful; a\n   precise null is a real and publishable finding. When the\n   interval is wide and includes important effects in either\n   direction, the study is uninformative in the range that\n   matters, and saying so is the honest report. Presenting an\n   underpowered null as evidence of no effect is a\n   consequential and common misreport, and the statistician is\n   usually the only person positioned to prevent it.\n3. Three things, all of which this book has argued for on\n   other grounds. A pre-specified analysis plan tagged in Git\n   before data lock (@sec-analysis-plan), so that you can\n   demonstrate which analysis was primary and when it was\n   fixed. A compendium that rebuilds with one command\n   (@sec-rrtools, @sec-zzcollab), so that changing the\n   exclusion criterion is an edit and a re-render rather than\n   an archaeological expedition. And a pinned environment\n   (@sec-renv, @sec-docker), so that the re-run six months\n   later produces the published numbers rather than subtly\n   different ones you then have to explain. Without them, the\n   reviewer's request is a week of reconstruction and a\n   discrepancy you cannot account for.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}